### PR TITLE
Plugins.Taudem/Hydrology.cs RunTaudem function does not execute corre…

### LINKED ISSUE #1496: DotSpatial.Plugins.Taudem/Hydrology.cs RunTaudem function does not execute correctly
The function  RunTaudem in master/Source/Extensions/DotSpatial.Plugins.Taudem/Hydrology.cs#L1746.
This function does not execute correctly.
In .Net Framework Process.StartInfo.UseShellExecute property default value is true，but in .Net 6.0,default value is false。we need set it by code。

var tfc = new TempFileCollection();
var tempFile = tfc.AddExtension("txt");
var taudemProcess = new Process
{
    StartInfo =
    {
        **_UseShellExecute = true,_**
        CreateNoWindow = true,
        WindowStyle = ProcessWindowStyle.Minimized,
        WorkingDirectory = TaudemExeDir(),
        FileName = "runtaudem.bat",
        Arguments = Quote(tempFile) + " mpiexec -n " + numProc.ToString(CultureInfo.InvariantCulture) + " " + command + " " + parameters
    }
};
taudemProcess.Start();
taudemProcess.WaitForExit();

### PR DESCRIPTION
**Pull request by mytudousi**
…ctly (#1496)
The function RunTaudem in master/Source/Extensions/DotSpatial.Plugins.Taudem/Hydrology.cs#L1746.
This function does not execute correctly.
Fixes #1496 

### Checklist

- [ ] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:
In .Net Framework Process.StartInfo.UseShellExecute property default value is true，but in .Net 6.0,default value is false。
So,in file file Hydrology.cs, i add code "UseShellExecute = true" on line1754 and 1772.

### CODE REVIEW

**Comment by jany-tenaj** [comment]
please update the changelog and add yourself to the contributors

**Comment by mytudousi** [comment]
> 

sorry，I'm not sure I understand what you mean.This is my first time contributing code to github.
I found it in a search,i just pull request,and wait for the owner to process it.
I gave it a try,can't find how to update changedlog.md. 
If it is convenient, could you please tell me in detail what I should do?
thanks.

**Comment by jany-tenaj** [comment]
I updated the changelog for you. You can simply edit it in visual studio or any other text editor and it would get pushed with your code files. You can also update it here on github. If you have a look at the file you have an edit button on the top right corner.

Please add yourself to the [Contributors](https://github.com/mytudousi/DotSpatial/blob/master/Contributors).

**Comment by mytudousi** [comment]
I kow how to do,thank you.

**Pull request merged**
