### PR TITLE
Fixed angle calculation for second and third quadrant

### LINKED ISSUE #1404: Vector angle theta returns different angle
### Steps to reproduce

When i create theese instances i get the wrong angle for theta

var vector = new Vector(2.0, new DotSpatial.Topology.Angle(1.04719));

vector = new Vector(2.0, new DotSpatial.Topology.Angle(2.09439));

vector = new Vector(2.0, new DotSpatial.Topology.Angle(-1.04719));

vector = new Vector(2.0, new DotSpatial.Topology.Angle(-2.09439));

DotSpatial version: 

### Expected behaviour

It should show the correct angle for each instance

### Actual behaviour

I get theese angles for theta

1.04719

4.1887953071795865 corrected -2,09439530717

5.2359953071795866 corrected -1,0471953071

2.09439

### PR DESCRIPTION
**Pull request by mathias13**
Fixes #1404 .

### Checklist

- [x] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by jany-tenaj** [comment]
@mathias13  I don't see any examples or tests. Please add them. Furthermore add this fix to the changelog and add yourself to the contributors.

**Comment by mathias13** [comment]
No problem, where should i put the unit test? There is no namespace related to NTSExtension, should i create one from scratch.

**Comment by jany-tenaj** [comment]
Yes it would make sense to create such a test project. But I remembered that I found Vector2d and Vector3d in NetTopologySuite. Please check, whether you can use one of those instead of Vector. If Vector2d and Vector3d can be used to replace Vector, I'd like to remove Vector instead of correcting existing mistakes. Vector was taken from DotSpatial.Topology which was an earlier port of NetTopologySuite. So basically it shouldn't be inside DotSpatial, but ended up in NtsExtensions because I couldn't find a suitable class in the current NetTopologySuite.

**Comment by mathias13** [comment]
I have created unit tests for all quadrants and they all pass. I will look into NetTopologySuite and migrate everything from DotSpatial.Topology. It seems to be the same code?

**Comment by jany-tenaj** [comment]
@mathias13 If possible you can simply upgrade your code to the current master. Then you'll see some things in your own code will have to be fixed because of the switch from DotSpatial.NetTopologySuite to NetTopologySuite.

**Comment by jany-tenaj** [comment]
added your changes into master

**Pull request closed without merging**
