### PR TITLE
DotSpatial Projections net472 and netstandard2.0

### PR DESCRIPTION
**Pull request by inforithmics**
Fixes # .

### Checklist

- [x] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Targets DotSpatial Projections To net472 and netstandard2.0 
  For having an official nuget
  https://www.nuget.org/packages/DotSpatial.Projections.NetStandard/

### CODE REVIEW

**Comment by jany-tenaj** [comment]
No idea what you are trying to do but it doesn't look as if we should accept this.

**Comment by inforithmics** [comment]
Reasons for accepting this. Support on Mobile Devices and .NET 6.

**Comment by inforithmics** [comment]
Workaround for reference the official DotSptial.Projections Project in NetStandard 2.0 Project

```
<ItemGroup>
    <PackageReference Include="DotSpatial.Projections" Version="3.0.0" IncludeAssets="None" ExcludeAssets="All" PrivateAssets="None" GeneratePathProperty="true" NoWarn="NU1202;NU1701"/>
  </ItemGroup>

  <!--Ignore nuget errors and reference the assembly directly -->
  <ItemGroup>
    <Reference Include="DotSpatial.Projections, Version=3.0.0.0, Culture=neutral, PublicKeyToken=272632bddd08a38b">
      <HintPath>$(PkgDotSpatial_Projections)\lib\net472\DotSpatial.Projections.dll</HintPath>
    </Reference>
  </ItemGroup>
```

**Comment by jany-tenaj** [comment]
@inforithmics No idea why I should accept something that removes all cs files from the project. And we have a mostly finished .Net 6 release in the MoveDsToNet6 branch.

**Comment by inforithmics** [comment]
The *.cs Files are not removed They are included by convention. When you open the Pull Request you will see that all cs Files are still in the project, but not anymore listed specifically.

See the Documentation of the new csproj File Format.
https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview

Thanks for the Tip about the MoveDsToNet6 Branch I will have a look at it. I think this is the Future. For all .NET Development.

**Comment by inforithmics** [comment]
Great work on the MoveDsToNet6 Branch. Would you accept there a Pull request to use NetStandard2.0 Or to MultiTarget it to NET4.7.2,NetStandard2.0, NET6.0?

**Comment by inforithmics** [comment]
Change This
`<TargetFramework>net6.0</TargetFramework>`
To This
`<TargetFrameworks>net472;netstandard2.0;net6.0</TargetFrameworks>`

**Comment by jany-tenaj** [comment]
If you are sure this will work without error, we can accept this.

**Comment by inforithmics** [comment]
Then I'll make a pull request. 
The main change would be, when having more than one target the output changes from bin\debug to \bin\debug\net6.0 and \bin\debug\netstandard2.0

**Comment by jany-tenaj** [comment]
Not good. Currently everything is put to bin\debug. If this gets compiled somewhere else it will be missing from bin\debug. So make sure the .net6 version still goes to bin\debug.

**Comment by inforithmics** [comment]
I think a can special case this with a custom output folder for .net 6.0 to going into bin\debug and .netstandard 2.0 to \bin\debug\netstandard2.0

**Pull request closed without merging**
