### PR TITLE
Additional sufficient criteria for projections equality?

### PR DESCRIPTION
**Pull request by pedwik**
Suggestion: Additional equality conditions for two Projections.

If central meridian, spheroid member values and unit member values are equal, is that a sufficient condition (but not necessary) for two projections to be considered equivalent? If so, I propose to change the Projections.Equals method. 

Also, if the authority codes are the same for two projections, it should be safe to conclude that they are equal.

### CODE REVIEW

**Comment by mogikanin** [comment]
What are use-cases you are trying to cover with this patch?

Can't imagine situation, when esri\proj4 strings are different, but authority codes are same.
Regarding to meridians, datums and units. Can you guarantee that two  projections are fully equals, i.e. produces the same coordinates in reprojection in all possible cases, if they have 1) different esri\proj4 representation, 2) different epsg codes, 3) but same meridians,datums, units?

**Comment by pedwik** [comment]
Isn't it so that the authority codes can be the same but the esri/proj4 strings can be different depending on what EPSG db version was used when the user GIS data was created? So a user can have a shape-file with and older version of a proj4 string. 

Concerning the meridians, datums and unit, this was only a question, not a statement. I realize I should have added this issue as a discussion issue, instead of a pull request, sorry.

The proj4 strings should be updated to version 8.9, don't you think?

**Comment by mogikanin** [comment]
Yes, better post such things to discussions\issue tracker.
> The proj4 strings should be updated to version 8.9

Good idea.

**Comment by pedwik** [comment]
Should I add the updating of proj4 strings as an issue, or have you taken care of it yourself?

**Comment by mogikanin** [comment]
Yes, please do it

**Pull request closed without merging**
