### PR TITLE
Bugfix affine coefficients

### PR DESCRIPTION
**Pull request by ghgetonup**
Fixes # 822.

### Checklist

- [yes ] I have included examples or tests
- [yes ] I have updated the change log
- [no ] I am listed in the CONTRIBUTORS file
- [ ?] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:
Fixed code to make it consistent with the first and fourth affine coefficients being the coordinates of the center of the top-left cell (as opposed to top-left of top-left cell)

### CODE REVIEW

**Comment by mogikanin** [comment]
@ghgetonup do you want to add yourself into CONTRIBUTORS file?

**Comment by mogikanin** [comment]
@ghgetonup One more thing. `_dataset.GetGeoTransform()` used in some other places. I think there also presented same error. Lets fix these places too?
* GdalImage.cs, line 126
* GdalImageSource.cs, line 185
* GdalTiledImage.cs, line 70

**Comment by ghgetonup** [comment]
Yes makes sense to fix those as well, I'll update...

**Comment by ghgetonup** [comment]
I noticed that there was already a method to shift origin of the affine coefficients, namely AffineTransform.TransformToCorner()), so I'm using this now to adjust the origin in the various Gdal*.cs sources. I changed input arguments of the method from int to double to allow for fractional rows and columns.

**Comment by mogikanin** [comment]
I've merged it into master. Thanks for the pull request!
P.S. @ghgetonup if you want to be added into CONTRIBUTORS files, just let me know :)

**Pull request merged**
