### PR TITLE
Update proj4string sweden

### PR DESCRIPTION
**Pull request by pedwik**
Copied the proj4string from Proj4Net-projekt. They include the towgs parameter which fixes repojections erros (issue #861). Also updated AuthorityCodeToProj4.ds.

### CODE REVIEW

**Comment by mogikanin** [comment]
All is fine. Remains only update changelog and contributors files.

**Comment by pedwik** [comment]
I created a pull request för each one of them, but when checking the pull
request info on the website, the file change refers to the first one I
committed yesterday (with the optional parameters for FromProj4String)

2016-10-03 6:25 GMT+02:00 Max Miroshnikov <notifications@github.com>:

**Comment by mogikanin** [comment]
No need create pull request for each one. Simply commit them into the `pedwik:update-proj4string-Sweden` branch. They automatically will appear here, in pull request.

**Comment by pedwik** [comment]
I have done that now but I cannot see any changes: 
image

**Comment by pedwik** [comment]
I now used the Commit changes alternative in the bottom-left-corner of the GUI, but I cannot see that the info has propagated to the pull request..

**Comment by mogikanin** [comment]
Look - https://github.com/pedwik/DotSpatial/commits/update_proj4string_Sweden
your commit already there.
But you need to commit changes into `update-proj4string-Sweden` branch, not into `update_proj4string_Sweden`.

**Comment by mogikanin** [comment]
All is fine now :) Do nothing anymore

**Pull request merged**
