### PR TITLE
Added support to read formatted ESRI shape files

### PR DESCRIPTION
**Pull request by mkaring**
Implements #793.

### Changes proposed in this pull request:

- Added the actual change in ProjectionInfo.cs where the entire file is read instead of just the first line
- Added a test to check if reading a formatted projection file and a standard projection file are properly read

### CODE REVIEW

**Comment by mogikanin** [comment]
Martin, there is a build error.

**Comment by mogikanin** [comment]
Errors and Failures:
1) Test Error : DotSpatial.Projections.Tests.ProjectionInfoTests.ReadProjectionFile("StandardProjectionFile")
   System.InvalidOperationException : Resource was of type 'ByteArray' instead of String - call GetObject instead.
   at System.Resources.ResourceReader.LoadString(Int32 pos)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.RuntimeResourceSet.GetString(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at DotSpatial.Projections.Tests.ProjectionInfoTests.ReadProjectionFile(String resourceName) in C:\projects\dotspatial\source\DotSpatial.Projections.Tests\ProjectionInfoTests.cs:line 163

**Comment by mkaring** [comment]
Because I was not looking out when adding the second file to the test case. Sorry about that. Should work now. Lets see what the build server has to say about it.

**Comment by mogikanin** [comment]
Thanks :)

**Pull request merged**
