### PR TITLE
Polygon label on perimeter of feature

### LINKED ISSUE #1211: Polygon label on perimeter of feature
*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description
I often use polygons to display range rings. That is to say I generate an ellipse around a central point with radius = x. Drawing the label in the center of the polygon doesn't look quite right for this type of usage. I would like to present the labels at the perimeter of the polygon. My feature request is a boundary LabelPlacementMethod for polygons please. As a side note, if someone can suggest where i can start looking to add this please let me know that as well. Thank you so much for a fantastic GIS framework.

image

### PR DESCRIPTION
**Pull request by sindizzy**
This modification introduces a label placement around the perimeter of a polygon feature. When the user employs this label placement method the code basically treats the outer ring of a polygon feature as a series of line segments and uses most of the polyline logic.

Implemented was a new variation of the rotation angle. The current code calculates it from the segment and uses ATAN. That works for all the calculations except when it comes to the inside/outside of a polygon since it loses the directionality. To account for that a new calculation was introduced with ATAN2 and called theta.

The polygon requires this angle with directionality so that we can determine which side is inside or outside the polygon. The only place theta is used is in the Position method and it doesn't get used for text rotation. All we need theta for is to determine which direction to offset the text relative to the segment. Basically logic to determine if the text is above or below the line.

The DotSpatial.Controls.MapLabelLayer is great code but could use a refactoring at some point. Of note is the multiple calls to the GetSegment method which could be needless overhead. I could envision that DotSpatial could be modified to allow different labeling engines much like a plugin.

For now I think this new label placement method is a good starting point for further work like optimal placement on the perimeter rather than along the first, middle, last, or longest segment. This can be seen in the sample project where the label is always placed on the longest segment. This is only in the UI as the developer can set them as they wish in code. This is due to LabelPlacementMethod and LineLabelPlacementMethod not being mutually exclusive. Perhaps a new SegmentLabelPlacementMethod would resolve this.

Fixes #1211 

### Checklist

- [x] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [ ] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Introduction of a label placement around the perimeter of a polygon feature

### CODE REVIEW

**Comment by sindizzy** [comment]
I have a couple of pull requests with this type of conflict with the changelog. I've based all my modifications on the same source so not sure why this happens. How can I correct it?

**Comment by jany-tenaj** [comment]
@sindizzy This conflict shows up whenever we include a pull request... It basically says that the line you added to the changelog here is different from the line that was added to the changelog in master. No idea why Github is not able to merge this whitout showing it as conflict.

It basically makes only sense to fix it shortly before we include the pull request because otherwise it would rise up again if we include other fixes in between.

**Comment by sindizzy** [comment]
I see. This happened with another pull request and i was unable to resolve it so i just deleted it and will upload at another time. Is there a way that I can temporarily fix this or will this change pass the checks?

**Comment by jany-tenaj** [comment]
@sindizzy I'll fix the changelog when I have time to take a look at this pull request. Currently it's to large to marge without testing whether it works, but I'm still swamped with work.

**Comment by sindizzy** [comment]
Closed this PR. Will wait until https://github.com/DotSpatial/DotSpatial/pull/1466 gets merged so that I can refactor the logic.

**Pull request closed without merging**
